USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS AIRLINE_DB;

USE DATABASE AIRLINE_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS CORE_DATA;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS UTILS;

CREATE OR REPLACE FILE FORMAT RAW_DATA.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RAW_DATA.AIRLINE_STAGE
    FILE_FORMAT = RAW_DATA.CSV_FORMAT;

CREATE OR REPLACE TABLE UTILS.AUDIT_LOG (
    LOG_ID INT IDENTITY(1,1),
    PROCESS_NAME VARCHAR,
    LOG_LEVEL VARCHAR,
    MESSAGE VARCHAR,
    AFFECTED_ROWS INT,
    LOG_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);