USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE OR REPLACE PROCEDURE UTILS.LOAD_CORE_FLIGHTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INT;
BEGIN

    INSERT INTO CORE_DATA.DIM_PILOTS (PILOT_NAME)
    SELECT DISTINCT PILOT_NAME 
    FROM RAW_DATA.AIRLINE_FLIGHTS_STREAM 
    WHERE PILOT_NAME IS NOT NULL 
    AND METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE
    AND PILOT_NAME NOT IN (SELECT PILOT_NAME FROM CORE_DATA.DIM_PILOTS);

    INSERT INTO CORE_DATA.DIM_AIRPORTS (AIRPORT_NAME, COUNTRY_NAME, CONTINENT)
    SELECT DISTINCT AIRPORT_NAME, COUNTRY_NAME, AIRPORT_CONTINENT
    FROM RAW_DATA.AIRLINE_FLIGHTS_STREAM 
    WHERE AIRPORT_NAME IS NOT NULL
    AND METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE
    AND AIRPORT_NAME NOT IN (SELECT AIRPORT_NAME FROM CORE_DATA.DIM_AIRPORTS);

    INSERT INTO CORE_DATA.DIM_PASSENGERS (PASSENGER_ID_CSV, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
    SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY
    FROM RAW_DATA.AIRLINE_FLIGHTS_STREAM
    WHERE PASSENGER_ID IS NOT NULL
    AND METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE
    AND PASSENGER_ID NOT IN (SELECT PASSENGER_ID_CSV FROM CORE_DATA.DIM_PASSENGERS);
    
    INSERT INTO CORE_DATA.FACT_FLIGHTS (
        FLIGHT_ID, PASSENGER_KEY, DEPARTURE_AIRPORT_KEY, PILOT_KEY, DEPARTURE_DATE, FLIGHT_STATUS
    )
    SELECT 
        MD5(S.PASSENGER_ID || S.DEPARTURE_DATE || S.AIRPORT_NAME),
        P.PASSENGER_KEY,
        A.AIRPORT_KEY,
        PL.PILOT_KEY,
        TRY_TO_DATE(S.DEPARTURE_DATE, 'MM/DD/YYYY'),
        S.FLIGHT_STATUS
    FROM RAW_DATA.AIRLINE_FLIGHTS_STREAM S
    LEFT JOIN CORE_DATA.DIM_PASSENGERS P ON S.PASSENGER_ID = P.PASSENGER_ID_CSV
    LEFT JOIN CORE_DATA.DIM_AIRPORTS A ON S.AIRPORT_NAME = A.AIRPORT_NAME
    LEFT JOIN CORE_DATA.DIM_PILOTS PL ON S.PILOT_NAME = PL.PILOT_NAME
    WHERE S.METADATA$ACTION = 'INSERT' AND S.METADATA$ISUPDATE = FALSE;

    rows_inserted := SQLROWCOUNT;

    INSERT INTO UTILS.AUDIT_LOG (PROCESS_NAME, LOG_LEVEL, MESSAGE, AFFECTED_ROWS)
    VALUES ('LOAD_CORE_STAR_SCHEMA', 'INFO', 'Loaded Facts and Dims', :rows_inserted);

    COMMIT;

    RETURN 'Success: Star Schema loaded. Rows: ' || :rows_inserted;
END;
$$;