USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE ROLE IF NOT EXISTS US_MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS CN_MANAGER_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE US_MANAGER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CN_MANAGER_ROLE;

GRANT USAGE ON DATABASE AIRLINE_DB TO ROLE US_MANAGER_ROLE;
GRANT USAGE ON DATABASE AIRLINE_DB TO ROLE CN_MANAGER_ROLE;

GRANT USAGE ON SCHEMA AIRLINE_DB.CORE_DATA TO ROLE US_MANAGER_ROLE;
GRANT USAGE ON SCHEMA AIRLINE_DB.CORE_DATA TO ROLE CN_MANAGER_ROLE;

GRANT USAGE ON SCHEMA AIRLINE_DB.UTILS TO ROLE US_MANAGER_ROLE;
GRANT USAGE ON SCHEMA AIRLINE_DB.UTILS TO ROLE CN_MANAGER_ROLE;

GRANT SELECT ON TABLE UTILS.ACCESS_RULES TO ROLE US_MANAGER_ROLE;
GRANT SELECT ON TABLE UTILS.ACCESS_RULES TO ROLE CN_MANAGER_ROLE;

GRANT SELECT ON VIEW CORE_DATA.SECURE_FLIGHTS_REPORT TO ROLE US_MANAGER_ROLE;
GRANT SELECT ON VIEW CORE_DATA.SECURE_FLIGHTS_REPORT TO ROLE CN_MANAGER_ROLE;

GRANT ROLE US_MANAGER_ROLE TO USER RASTSISLAUDOUHI;
GRANT ROLE CN_MANAGER_ROLE TO USER RASTSISLAUDOUHI;