USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE OR REPLACE TABLE UTILS.ACCESS_RULES (
    ROLE_NAME VARCHAR,
    ALLOWED_COUNTRY VARCHAR
);

INSERT INTO UTILS.ACCESS_RULES (ROLE_NAME, ALLOWED_COUNTRY)
VALUES 
    ('US_MANAGER_ROLE', 'United States'),
    ('CN_MANAGER_ROLE', 'China');

CREATE OR REPLACE ROW ACCESS POLICY UTILS.COUNTRY_POLICY 
AS (country_value VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() = 'ACCOUNTADMIN'
  OR
  EXISTS (
      SELECT 1 FROM UTILS.ACCESS_RULES
      WHERE ROLE_NAME = CURRENT_ROLE()
      AND ALLOWED_COUNTRY = country_value
  );

CREATE OR REPLACE SECURE VIEW CORE_DATA.SECURE_FLIGHTS_REPORT AS
SELECT 
    F.FLIGHT_ID,
    F.DEPARTURE_DATE,
    A.COUNTRY_NAME as DEPARTURE_COUNTRY,
    A.AIRPORT_NAME,
    P.FIRST_NAME,
    P.LAST_NAME
FROM CORE_DATA.FACT_FLIGHTS F
JOIN CORE_DATA.DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_KEY = A.AIRPORT_KEY
JOIN CORE_DATA.DIM_PASSENGERS P ON F.PASSENGER_KEY = P.PASSENGER_KEY;

ALTER VIEW CORE_DATA.SECURE_FLIGHTS_REPORT
ADD ROW ACCESS POLICY UTILS.COUNTRY_POLICY ON (DEPARTURE_COUNTRY);