USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE OR REPLACE PROCEDURE UTILS.LOAD_RAW_AIRLINE_DATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE RAW_DATA.AIRLINE_FLIGHTS;

    COPY INTO RAW_DATA.AIRLINE_FLIGHTS
    FROM @RAW_DATA.AIRLINE_STAGE
    FILE_FORMAT = (FORMAT_NAME = RAW_DATA.CSV_FORMAT)
    ON_ERROR = 'SKIP_FILE';
    
    COMMIT;

    RETURN 'Data successfully loaded into RAW_DATA.AIRLINE_FLIGHTS';
END;
$$;