USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

--DROP TABLE ANALYTICS.FLIGHT_STATS_BY_COUNTRY;

UNDROP TABLE ANALYTICS.FLIGHT_STATS_BY_COUNTRY;

CREATE OR REPLACE TABLE CORE_DATA.DIM_PASSENGERS_BACKUP 
CLONE CORE_DATA.DIM_PASSENGERS 
AT(OFFSET => -60*5);