USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE OR REPLACE STREAM RAW_DATA.AIRLINE_FLIGHTS_STREAM 
ON TABLE RAW_DATA.AIRLINE_FLIGHTS;

CREATE OR REPLACE TABLE CORE_DATA.DIM_PASSENGERS (
    PASSENGER_KEY INT IDENTITY(1,1),
    PASSENGER_ID_CSV VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    UNIQUE (PASSENGER_ID_CSV)
);

CREATE OR REPLACE TABLE CORE_DATA.DIM_AIRPORTS (
    AIRPORT_KEY INT IDENTITY(1,1),
    AIRPORT_NAME VARCHAR,
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR,
    UNIQUE (AIRPORT_NAME)
);

CREATE OR REPLACE TABLE CORE_DATA.DIM_PILOTS (
    PILOT_KEY INT IDENTITY(1,1),
    PILOT_NAME VARCHAR,
    UNIQUE (PILOT_NAME)
);

CREATE OR REPLACE TABLE CORE_DATA.FACT_FLIGHTS (
    FLIGHT_ID VARCHAR,
    PASSENGER_KEY INT,
    DEPARTURE_AIRPORT_KEY INT,
    ARRIVAL_AIRPORT_KEY INT,
    PILOT_KEY INT,
    DEPARTURE_DATE DATE,
    FLIGHT_STATUS VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)