--USE ROLE ACCOUNTADMIN;
--USE WAREHOUSE COMPUTE_WH;

--USE ROLE US_MANAGER_ROLE;
--USE WAREHOUSE COMPUTE_WH;

USE ROLE CN_MANAGER_ROLE;
USE WAREHOUSE COMPUTE_WH;

SELECT 
    DEPARTURE_COUNTRY, 
    COUNT(*) as FLIGHTS_COUNT
FROM CORE_DATA.SECURE_FLIGHTS_REPORT
GROUP BY DEPARTURE_COUNTRY;