USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;

CREATE OR REPLACE PROCEDURE UTILS.LOAD_ANALYTICS_STATS()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INT;
BEGIN
    TRUNCATE TABLE ANALYTICS.FLIGHT_STATS_BY_COUNTRY;

    INSERT INTO ANALYTICS.FLIGHT_STATS_BY_COUNTRY (
        REPORT_DATE, 
        DESTINATION_COUNTRY, 
        TOTAL_FLIGHTS, 
        UNIQUE_PASSENGERS,
        AVG_PASSENGER_AGE
    )
    SELECT 
        F.DEPARTURE_DATE,
        A.COUNTRY_NAME,
        COUNT(F.FLIGHT_ID) as TOTAL_FLIGHTS,
        COUNT(DISTINCT P.PASSENGER_ID_CSV) as UNIQUE_PASSENGERS,
        AVG(P.AGE) as AVG_PASSENGER_AGE
        FROM CORE_DATA.FACT_FLIGHTS F
    JOIN CORE_DATA.DIM_AIRPORTS A ON F.DEPARTURE_AIRPORT_KEY = A.AIRPORT_KEY
    JOIN CORE_DATA.DIM_PASSENGERS P ON F.PASSENGER_KEY = P.PASSENGER_KEY
    GROUP BY 1, 2;

    rows_inserted := SQLROWCOUNT;

    INSERT INTO UTILS.AUDIT_LOG (PROCESS_NAME, LOG_LEVEL, MESSAGE, AFFECTED_ROWS)
    VALUES ('LOAD_ANALYTICS_STATS', 'INFO', 'Aggregated data loaded into Analytics', :rows_inserted);

    COMMIT;

    RETURN 'Success: Analytics updated. Rows: ' || :rows_inserted;
END;
$$;