USE ROLE ACCOUNTADMIN;
USE DATABASE AIRLINE_DB;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.FLIGHT_STATS_BY_COUNTRY (
    REPORT_DATE DATE,
    DESTINATION_COUNTRY VARCHAR,
    TOTAL_FLIGHTS INT,
    UNIQUE_PASSENGERS INT,
    AVG_PASSENGER_AGE DECIMAL(5,2),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);